trigger:
  branches:
    include:
    - main
  paths:
    include:
    - network

pool:
  vmImage: 'Ubuntu-latest'

stages:

- stage: Validate
  displayName: 'QA Code'
  jobs:
  - job: Linter
    displayName: 'Linter Test'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd network
          terraform init
          terraform validate
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AZDO_GITHUB_SERVICE_CONNECTION_PAT: $(AZDO_GITHUB_SERVICE_CONNECTION_PAT)
        AZDO_ORG_SERVICE_URL: $(AZDO_ORG_SERVICE_URL)
        TFE_TOKEN: $(TFE_TOKEN)
        TFE_ORG: 'VillaMTB'
