trigger:
  branches:
    include:
    - main
  paths:
    include:
    - network

pool:
  vmImage: 'Ubuntu-latest'

stages:

- stage: Validate
  displayName: 'QA Code'
  jobs:
  - job: Linter
    displayName: 'Linter Test'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd network
          terraform init
          terraform validate

- stage: Plan
  jobs:
  - job: Speculative
    displayName: 'Run Speculative Plan'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd network
          terraform init
          terraform plan

- stage: Apply
  jobs:
  - job: Deploy
    displayName: 'Deploy Infrastructure'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd network
          terraform init
          terraform apply -auto-approve